# Generated by Django 4.1.13 on 2023-12-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellido1',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido2',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='calleynumero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estadoCivil',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaAlta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
    ]
